- name: install docker
  hosts: all
  become: true
  roles:
    - docker_install

- name: initialise docker swarm
  hosts: swarm-manager
  become: true
  roles:
    - docker_init

- name: add workers to the swarm
  hosts: swarm-workers
  become: true
  roles:
    - docker_add_swarm